apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ArthurPieri/ws-stack-dados-k8s.git'
    path: infra/src/helm-charts/minio-operator
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
      name: 'do-sfo3-ap-k8s'
      namespace: deepstorage
      server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
